FROM node:16.20.2-buster

WORKDIR /app

COPY package*.json ./
COPY ./.env ./.env

RUN npm install
RUN npm install pm2 -g

COPY . .

RUN npm run build:staging 

EXPOSE 3000

CMD ["pm2-runtime", "start", "npm", "--name", "frontend_staging",  "--", "run", "start:staging"]
